config/routes.rb
Rails.application.routes.draw do

  resources :power_forms

  get 'static_pages/home'

  get 'static_pages/about'

  root 'power_forms#new'

end

app/models/power_form.rb
class PowerForm < ActiveRecord::Base

  validate :date_range_correct?

  def date_range_correct?

    if tstart < DateTime.strptime('2011-04-18T09:22:00', '%Y-%m-%dT%H:%M:%S') or tstart > DateTime.strptime('2011-05-24T15:57:00', '%Y-%m-%dT%H:%M:%S')
      errors.add(:tstart, 'Please enter a start date within a valid range.')
    end

    if tend < DateTime.strptime('2011-04-18T09:22:00', '%Y-%m-%dT%H:%M:%S') or tend > DateTime.strptime('2011-05-24T15:57:00', '%Y-%m-%dT%H:%M:%S')
      errors.add(:tend, 'Please enter a end date within a valid range.')
    end

    if tstart > tend
      errors.add(:tstart, 'Please ensure that your start date comes before your end date.')
    end

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def hello
    render text: "hello world!"
  end

end

app/controllers/power_forms_controller.rb
class PowerFormsController < ApplicationController
  before_action :set_power_form, only: [:show, :edit, :update, :destroy]


  # GET /power_forms
  # GET /power_forms.json
  def index
    @power_forms = PowerForm.all
  end

  # GET /power_forms/1
  # GET /power_forms/1.json
  def show
    #run code here
    require 'csv'

    appliance = @power_form.appliance
    tstart = @power_form.tstart.strftime("%Y%m%d-%H%M")
    tend = @power_form.tend.strftime("%Y%m%d-%H%M")
    call = "/home/mike/anaconda/bin/python2.7 script.py "+appliance+" "+tstart+" "+tend

    system(call)

    #load parameters here
    disag = CSV.read('/home/mike/workspace/data/disag_output.csv')
    disag_hash = Hash[disag]
    @disag = disag_hash

    mains = CSV.read('/home/mike/workspace/data/mains_sum.csv')
    mains_hash = Hash[mains]
    @mains = mains_hash

    @chart_title = "Disaggregated "+@power_form.appliance.gsub("_"," ").capitalize+" Power"

    f1_scores = CSV.read('/home/mike/workspace/data/f1_results.csv')
    @f1_score = f1_scores

    en_per_meter = CSV.read('/home/mike/workspace/data/pred_results.csv')
    @en_per_meter = en_per_meter

    total_energy = 0

    t_en_file = File.open('/home/mike/workspace/data/total_energy.txt','r')
    t_en_file.each_line do |line|
      total_energy = line
    end
    t_en_file.close()

    @total_energy = total_energy

    total_time = 0

    t_time_file = File.open('/home/mike/workspace/data/total_time.txt','r')
    t_time_file.each_line do |line|
      total_time = line
    end
    t_time_file.close()

    @total_time = total_time

  end

  # GET /power_forms/new
  def new
    @power_form = PowerForm.new
  end

  # GET /power_forms/1/edit
  def edit
  end

  # POST /power_forms
  # POST /power_forms.json
  def create



    @power_form = PowerForm.new(power_form_params)


    respond_to do |format|
      if @power_form.save
        format.html { redirect_to @power_form, notice: 'Power form was successfully created.' }
        format.json { render :show, status: :created, location: @power_form }

        else
        format.html { render :new }
        format.json { render json: @power_form.errors, status: :unprocessable_entity }

      end
    end

  end

  # PATCH/PUT /power_forms/1
  # PATCH/PUT /power_forms/1.json
  def update
    respond_to do |format|
      if @power_form.update(power_form_params)
        format.html { redirect_to @power_form, notice: 'Power form was successfully updated.' }
        format.json { render :show, status: :ok, location: @power_form }

      else
        format.html { render :edit }
        format.json { render json: @power_form.errors, status: :unprocessable_entity }
      end
    end

  end

  # DELETE /power_forms/1
  # DELETE /power_forms/1.json
  def destroy
    @power_form.destroy
    respond_to do |format|
      format.html { redirect_to power_forms_url, notice: 'Power form was successfully destroyed.' }
      format.json { head :no_content }

    end
  end




  private
    # Use callbacks to share common setup or constraints between actions.
    def set_power_form
      @power_form = PowerForm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def power_form_params
      params.require(:power_form).permit(:appliance, :tstart, :tend)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    #@mains_small = MAINS_CSV[3..-1 ]
    #@disag_output = DISAG_CSV[3..-1]
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/loader_helper.rb
module LoaderHelper
end

app/helpers/power_forms_helper.rb
module PowerFormsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Energy Management Through Power Disaggregation | ECSE 457 Group 20 Design Project
  </small>

  <nav>
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", static_pages_about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "McGill Energy Management", "#", id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",     root_path, id: "home_link"  %></li>
        <li><%= link_to "About",    static_pages_about_path, id: "about_link"  %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9}>
  <script src="//cdnjs.cloudfare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> <%= yield(:title)%> | ECSE 457 Energy Management Design Project</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <%= render 'layouts/shim'%>

</head>
<body>
<%= render 'layouts/header'%>
<div class="container">
  <%= yield %>
  <%= render 'layouts/footer' %>
</div>

</body>
</html>

app/views/power_forms/_form.html.erb
<%= form_for(@power_form) do |f| %>
  <% if @power_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@power_form.errors.count, "error") %> prohibited this power_form from being saved:</h2>
stance=10, bui
      <ul>
      <% @power_form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Select appliance to disaggregate" %><br>
    <%= f.select :appliance, options_for_select([["Fridge", "fridge"], ["Dish Washer", "dish_washer"], ["Sockets(1)", "sockets1"], ["Sockets(2)", "sockets2"],
        ["Lights(1)","light1"], ["Microwave","microwave"],
        ["Sockets(3)","sockets3"],["Lights(2)","light2"],["Lights(3)","light3"],["Washer Dryer","washer_dryer"],["Electric Oven","electric_oven"]]) %>
  </div>
  <div class="field">
    <%= f.label "Start time and date" %><br>
    <%= f.datetime_select :tstart, :start_year => 2011, :end_year => 2011 , :default => DateTime.new(2011,04,18,9,22)%>
  </div>
  <div class="field">
    <%= f.label "End time and date" %><br>
    <%= f.datetime_select :tend, :start_year => 2011, :end_year => 2011, :default => DateTime.new(2011,05,24,15,57)%>
  </div>

    <div class="actions">
      <%= f.submit "Disaggregate", :onclick => "$('#loading').show();"%>
    </div>

<% end %>

app/views/power_forms/_load.html.erb
<div id="loading"></div>

app/views/power_forms/application.html.erb
<h1>test</h1>

app/views/power_forms/edit.html.erb
<h1>Editing Power Form</h1>

<%= render 'form' %>

<%= link_to 'Show', @power_form %> |
<%= link_to 'Back', power_forms_path %>

app/views/power_forms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Power Forms</h1>

<table>
  <thead>
    <tr>
      <th>Appliance</th>
      <th>Tstart</th>
      <th>Tend</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @power_forms.each do |power_form| %>
      <tr>
        <td><%= power_form.appliance %></td>
        <td><%= power_form.tstart %></td>
        <td><%= power_form.tend %></td>
        <td><%= link_to 'Show', power_form %></td>
        <td><%= link_to 'Edit', edit_power_form_path(power_form) %></td>
        <td><%= link_to 'Destroy', power_form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Power form', new_power_form_path %>

app/views/power_forms/new.html.erb
<div id="wrap">

  <h1>Energy Management Through Power Disaggregation</h1>

  <div style= "height: 30px; clear: both;"></div>

    <div class = "center">

        <div style = "font-size: medium; text-align: left; float: left; width: 40%; padding-top: 20px;">


          Welcome to the home page of the <b><i>Energy Management through Power Disaggregation</i></b> design project.
          This web application will run a disaggregation algorithm on the total power usage measurements of
          a real residential building, <a href="http://redd.csail.mit.edu/">whose dataset is provided from researchers at MIT</a>.
          This disaggregation will estimate the total power used by the selected household appliance, giving an accurate representation of
          individual power consumption without the need to connect a physical sub-meter to the system.

          <br>
          <br>

          To get started, please select your disaggregation parameters
          using the form below. For more information about the project motivation and team please visit our
          <a href="ecse-457.ece.mcgill.ca/static_pages/about" > about page</a>. The disaggregation algorithms and processing
          used in this project are powered through the <a href="http://nilmtk.github.io/">Non-Intrusive Load-Monitoring Toolkit (NILMTK) </a>,
          an open source Python framework that utilizes machine-learning to find the best possible disaggregation results.

        </div>

      <div style = "text-align: center; float: right; width: 60%;">

        <figure>
          <img src="assets/hart.png", style="width:659px; height:358px;">
          <figcaption style="text-align: center; text-indent: 0px;">
            <i><b>
              Individual appliance load contributions on an aggregate signal (Hart, 1992)
          </b></i></figcaption>
        </figure>

      </div>

        <div style= "height: 60px; clear: both;"></div>

      <h1>Disaggregation Parameters</h1>

      <div style= "height: 50px; clear: both;"></div>

        <div id = "top_wrap">

            <div id="left_wrap">

              To begin please select the appliance of which you wish to see the disaggregated power usage signal. As
              the system is using a static dataset, please only choose date and time ranges of between
              <b>2011-April-18 09:22</b> and <b>2011-May-24 15:57</b>.

              <br><br>
              <b>Warning:</b> Depending on server load and internet connection, the process can take anywhere from <u>20-90</u>
              seconds.

            </div>


            <div id="right_wrap">

              <%= render 'form' %>

            </div>

          <div style= "height: 50px; clear: both;"></div>

        </div>


    </div>
</div>

<div id = "loading"></div>

app/views/power_forms/show.html.erb
<% provide(:title, "Home") %>



  <div class="center">

    <h1>Appliance Disaggregation Results</h1>

    <div style="height: 10px; clear: both;"></div>

    <body>
        <div style = "width: 100%; ">
            <div id="charts">

              <%= area_chart(@mains, {library:{hAxis:{title:"Time"}, vAxis:{title:"Apparent Power [VA]"}, title:"Building Mains Power"}} )%>

              <%= area_chart(@disag, {library:{hAxis:{title:"Time"}, vAxis:{title:"Active Power [kW]"}, title: @chart_title}} )%>

            </div>



            <h1>Disaggregation Metrics</h1>

            <div style= "height: 30px; clear: both;"></div>


            <div id="l_metrics">

              <%= pie_chart(@en_per_meter, {library:{title:"Total Energy Used Per Appliance [kWh]"}}) %>

              <div style="height:50px; clear: both;"></div>

                <div style = "text-align: center; font-size: large;">
                    Total predicted energy used [kWh] by the building: <%= @total_energy %>
                </div>


            </div>

            <div id = "r_metrics">

              <%= bar_chart(@f1_score , {library:{hAxis:{title:"Score"}, vAxis:{title:"Appliance"}, title:"F1 Accuracy Score per Appliance"}} ) %>

              <div style="height:50px; clear: both;"></div>

                <div style = "text-align: center; font-size: large;">
                    Total disaggregation script processing time [s]: <%= @total_time %>
                </div>

            </div>

          <div style="height:30px; clear: both;"></div>

        </div>
    </body>



  </div>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<h1>Project Team and Motivation</h1>
<div style="font-size:medium;">
  <div style="height: 10px; clear: both;"></div>

This web application is the final design project of group 20 for ECSE 457, Design Project II. Our supervisor is Francois Bouffard, and our
  project team consists of: Michael Milicevich, Irtaza Rizvi, Hans Zhang and Daniel Sayek. This project would not be
  without the mentorship of last year's project group, Christopher Tegho and Fiona Yuan.
  <br><br>
  Our web application is intended as a proof of concept that a web-based power disaggregation system can be feasible to
  implement. The original plan for the project was to install or receive real-time power usage data from the McGill
  University Rutherford Physics building- however, these plans fell through due to cost and time constraints and as a
  result our group made the decision to showcase the same functionality on a static dataset. It is our hope that this
  project can be continued on in the following semesters, this time utilizing our disaggregation application to run
  on real-time McGill university building data.
  <br><br>
 <b>Project Resources:</b><br>
  Disaggregation Algorithms and Toolkit: <a href="http://nilmtk.github.io/">Non-Intrusive Load-Monitoring Toolkit (NILMTK) </a><br>
  Energy Usage Dataset:  <a href="http://redd.csail.mit.edu/">Reference Energy Disaggregation Dataset (REDD)</a>

</div>


<div style="height: 50px; clear: both;"></div>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<div id = 'wrap'>

<div class="center">

  <h1>Energy Management through Power Disaggregation</h1>

  <div style="height: 30px; clear: both;"></div>

  <h2>This is the home page for the design project of Group 20 in ECSE 457.</h2>

  <body>



    <div id = "input_form">

      <div style="height: 50px; clear: both;"></div>
      <form>
        Appliance:&nbsp;
        <select name="appliance">
          <option value = "fridge">Fridge</option>
          <option value = "dish washer">Dish Washer</option>
          <option value = "sockets1">Sockets (1)</option>
          <option value = "sockets2">Sockets (2)</option>
          <option value = "light1">Lights (1)</option>
          <option value = "light2">Lights(2)</option>
          <option value = "microwave">Microwave</option>
          <option value = "electric space heater">Electric Space Heater</option>
          <option value = "electric stove">Electric Oven</option>
          <option value = "sockets3">Sockets (3)</option>
          <option value = "sockets4">Sockets (4)</option>
          <option value = "light2">Lights (3)</option>
          <option value = "light3">Lights (4)</option>
          <option value = "washer dryer">Washer Dryer</option>
          <option value = "electric oven">Electric Oven</option>
        </select>
        <br>
        <br>
        Start Time:
        <input type="datetime" name ="tstart">
        <br>
        <br>
        End Time:&nbsp;
        <input type="datetime" name="tend">
        <br>
        <br>

        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

        <input type="submit" value="Submit">

      </form>


    </div>

    <div style="height: 10px; clear: both;"></div>

  </body>

</div>

</div>